apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kv.fullname" . }}
  labels:
    {{- include "kv.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kv.fullname" . }}-pod-reader
  labels:
    {{- include "kv.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kv.fullname" . }}-pod-reader
  labels:
    {{- include "kv.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kv.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "kv.fullname" . }}-pod-reader
